# Generated by Django 6.0.4 on 2026-04-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_completed_at_task_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completion_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
