# Generated by Django 6.0.4 on 2026-04-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='allow_uploads',
            field=models.BooleanField(default=True, verbose_name='Permitir subir archivos'),
        ),
        migrations.AddField(
            model_name='team',
            name='allowed_extensions',
            field=models.JSONField(blank=True, default=list, verbose_name='Extensiones permitidas'),
        ),
        migrations.AddField(
            model_name='team',
            name='max_file_size',
            field=models.IntegerField(default=10, verbose_name='Tamaño máximo (MB)'),
        ),
    ]
